### ISSUE TITLE
Principes, standaarden en best-practices uit semester 3 toepassen

### ISSUE THREAD

**Issue by annelinderaadsheer** [annelinderaadsheer/i-love-web#15]

**Comment by annelinderaadsheer** [comment]
## Project opzetten SvelteKit

Voor het bouwen ben ik begonnen met het svelte project op te zetten. #1 

## Library indelen / componenten

Vervolgens heb ik na mijn ontwerp de componenten aangemaakt in de `src/components`.

- #5
- #6
- #8 
- #7 
- #14 

Ik heb na aanleiding van mijn inspiratie bord op Figma een css bestand met variabele kleuren die ik in mijn hele portfolio wil gebruiken aangemaakt in de `static/styles`. #9 

## CSS Variabelen

```CSS
:root {
    --color-light-pink: #f3e3cb;
    --color-pink: #ff9b9e;
    --color-red: #dd0222;
    --color-orange: #ff8a00;
    --color-yellow: #fcb207;
    --color-dark-pink: #ff6347;
    --color-white: #f2f2f2;
    --color-grey: #d1d1d1;
  }
```

## Responsive

- Ik heb bij elk component gebruik gemaakt van media queries om mijn portfolio responsive te maken. Ik ben begonnen met mobile first te bouwen dus ik heb gebruik gemaakt van `@media (min-width)`.

## Performance

- Ik heb Svelte gebruikt omdat het de code omzet naar snelle JS zonder veel extra belasting voor de browser, wat zorgt voor snellere laadtijden.
- Ik heb CSS-animaties gebruikt. Deze zijn lichter en sneller dan JS-animaties.
- Ik heb media queries toegepast om de lay-out aan te passen aan verschillende schermgroottes. Dit zorgt voor een betere ervaring op zowel desktop als mobiel en verbetert de snelheid door alleen de juiste styling te laden.

## Deployen via Vercel

Ik heb de site live gezet via Vercel: https://i-love-web-oazs.vercel.app



**Ik heb geprobeerd bij elk component die ik heb gebruikt op dezelfde manier te werken, en de componenten herbruikbaar te laten. Laten we bijvoorbeeld kijken naar de About.me en Skills component.**
