### ISSUE TITLE
Code skills toepassen

### ISSUE THREAD

**Issue by annelinderaadsheer** [annelinderaadsheer/i-love-web#16]

**Comment by annelinderaadsheer** [comment]
# Container queries

## AboutMe component

Container queries zijn een nieuwe CSS-functie waarmee je de stijl aanpast op basis van de grootte van de container waarin een element zich bevindt, in plaats van de schermgrootte. 

- Ik heb container queries toegevoegd om de tekstgrootte aan te passen op basis van de breedte van de container in de AboutMe sectie. 
- Ik heb` container-type: inline-size` alleen toegepast op de hoofdcontainer `.about-me-container`. De tekstgroottes en marges worden nu aangepast met container queries, afhankelijk van de breedte van de hoofdcontainer. De layout en responsiviteit blijven behouden dankzij de bestaande media queries, die de flexbox-instellingen beheren.
- Door container queries en media queries te combineren, heb ik een responsieve portfolio gemaakt die zich zowel aanpast aan de container waarin elementen zich bevinden als aan het scherm van de gebruiker.

```CSS
  .about-me-container {
    container-type: inline-size;  /* Container query wordt hier ingeschakeld */
    padding: 2rem;
    color: var(--color-dark-pink);
    background-color: var(--color-light-pink);
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }
```

```CSS
  /* Container Queries voor tekstgroottes en marges */
  @container (min-width: 320px) {
    .intro-1, .about-me-right p {
      font-size: 1rem;
    }
  }


  @container (min-width: 480px) {
    .intro-1, .about-me-right p {
      font-size: 1.1rem;
    }
  }


  @container (min-width: 768px) {
    .intro-1, .about-me-right p {
      font-size: 1.2rem;
    }
  }


  @container (min-width: 1024px) {
    .title {
      font-size: 2.5rem;
    }


    .intro-1, .about-me-right p {
      font-size: 1.3rem;
    }
  }


  @container (min-width: 1280px) {
    .about-me-container {
      padding: 4rem;
    }
    .photo-container {
      width: 60%;
    }


    .title {
      font-size: 3rem;
    }
    .intro-1, .about-me-right p {
      font-size: 1.4rem;
    }
  }


  @container (min-width: 1440px) {
    .about-me-container {
      padding: 4rem;
    }
    .photo-container {
      width: 60%;
    }
    .title {
      font-size: 3.5rem;
    }
    .intro-1, .about-me-right p {
      font-size: 1.5rem;
    }
  }


  @container (min-width: 1920px) {
    .about-me-container {
      padding: 5rem;
    }
    .photo-container {
      width: 50%;
    }
    .title {
      font-size: 4rem;
    }
    .intro-1, .about-me-right p {
      font-size: 1.6rem;
    }
  }
```

Bron: 
- https://css-tricks.com/css-container-queries/

**Comment by annelinderaadsheer** [comment]
# Fade-in scroll animatie

## Skills component 

Ik heb een scroll-triggered animatie toegevoegd die zorgt voor een vloeiend "fade-in en omhoog" effect bij de items in een lijst wanneer ze op de pagina verschijnen. 

De lijstitems (items in` .skills-list li`) worden een voor een zichtbaar door de animatie`fadeInUp`.
Elk item wordt iets later geanimeerd dan het vorige, wat een soort "opstijgend effect" creëert.

- `@media (prefers-reduced-motion: reduce):` Deze regel controleert of de gebruiker de voorkeur heeft om animaties niet te zien. Als dat het geval is, worden de animaties uitgeschakeld door `animation: none;` toe te passen, zodat de elementen meteen zichtbaar zijn zonder animaties.
- `@media (prefers-reduced-motion: no-preference):` Deze regel geldt voor gebruikers die geen voorkeur hiervoor hebben (dus ze willen animaties zien). Hier worden de animaties op de lijstitems toegepast, zodat de fade-in bewegingen worden afgespeeld.

```CSS
  /* Scroll-triggered animations */
  @media (prefers-reduced-motion: no-preference) {
    .skills-list li:nth-child(1) {
      animation: fadeInUp 0.6s ease forwards 0.2s;
    }


    .skills-list li:nth-child(2) {
      animation: fadeInUp 0.6s ease forwards 0.4s;
    }


    .skills-list li:nth-child(3) {
      animation: fadeInUp 0.6s ease forwards 0.6s;
    }


    .skills-list li:nth-child(4) {
      animation: fadeInUp 0.6s ease forwards 0.8s;
    }


    .skills-list li:nth-child(5) {
      animation: fadeInUp 0.6s ease forwards 1s;
    }


    .skills-list li:nth-child(6) {
      animation: fadeInUp 0.6s ease forwards 1.2s;
    }


    .skills-list li:nth-child(7) {
      animation: fadeInUp 0.6s ease forwards 1.4s;
    }


    .skills-list li:nth-child(8) {
      animation: fadeInUp 0.6s ease forwards 1.6s;
    }
  }


  /* Animation keyframes */
  @keyframes fadeInUp {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }


  /* Reduced Motion */
  @media (prefers-reduced-motion: reduce) {
    .skills-list li {
      opacity: 1;
      transform: none;
      animation: none;
    }
  }
```

Bronnen: 
- https://web.dev/articles/new-responsive#prefers-reduced-motion
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animations

**Comment by annelinderaadsheer** [comment]
# Carousel

## Projects component

Ik heb een carousel gemaakt voor mijn portfolio waarmee je eenvoudig kunt navigeren tussen mijn verschillende projecten. 

Deze carousel maakt gebruik van radio-buttons om van het ene project naar het andere te schakelen. 

Ik heb dit carousel gemaakt met HTML en CSS, waardoor dit carousel helemaal PE is, wat zorgt voor een betere laadtijd en een optimale gebruikerservaring.

**HTML**

```HTML
  <!-- Carousel -->
  <div id="carousel">
    <!-- Radio buttons als navigatie -->
    <input type="radio" id="slide1" name="carousel" checked>
    <input type="radio" id="slide2" name="carousel">
    
    <!-- Carousel items -->
    <div class="inner">
      <a href="https://github.com/annelinderaadsheer/lose-your-head-the-client-case" class="project-item button slide">
        <img src="/images/Redpers-logo.webp" alt="Redpers" class="project-logo">
      </a>
      <a href="https://github.com/annelinderaadsheer/oba" class="project-item button slide">
        <img src="/images/Oba-logo.webp" alt="Oba" class="project-logo">
      </a>
    </div>


    <!-- Bullets -->
    <div id="bullets">
      <label for="slide1"></label>
      <label for="slide2"></label>
    </div>
  </div>
```

**CSS**

```CSS
  /* Carousel */
  #carousel {
    position: relative;
    overflow: hidden;
    width: 100%;
    max-width: 800px;
    margin: 0 auto;
  }


  /* Verberg standaard radio buttons */
  #carousel input[type="radio"] {
    display: none;
}


  .inner {
    display: flex;
    transition: transform 0.5s ease;
  }


  .slide {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 300px;
    flex: 0 0 100%;
  }


  .project-logo {
    max-width: 80%;
    max-height: 80%;
  }


  /* Bullets styling */
  #bullets {
    display: flex;
    justify-content: center;
    margin-top: 1rem;
  }


  #bullets label {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background-color: #ccc;
    margin: 0 5px;
    display: inline-block;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }


  #bullets input[type="radio"]:checked + label {
    background-color: #444;
  }


  #bullets label:hover {
    background-color: #999;
  }


  /* Verschuift de carousel naar links of rechts afhankelijk van de geselecteerde radio-button */
  input[type="radio"]:nth-child(1):checked ~ .inner {
    transform: translateX(0%);
  }
  input[type="radio"]:nth-child(2):checked ~ .inner {
    transform: translateX(-100%);
  }
  
  input[type="radio"]:nth-child(3):checked ~ .inner {
    transform: translateX(-200%);
  }
```
