### ISSUE TITLE
CSS variabele toevoegen

### ISSUE THREAD

**Issue by annelinderaadsheer** [annelinderaadsheer/i-love-web#9]

**Comment by annelinderaadsheer** [comment]
```CSS
:root {
    --color-light-pink: #f3e3cb;
    --color-pink: #ff9b9e;
    --color-red: #dd0222;
    --color-orange: #ff8a00;
    --color-yellow: #fcb207;
    --color-dark-pink: #ff6347;
    --color-white: #f2f2f2;
    --color-grey: #d1d1d1;
  }
```
